"""Every tunable constant in the package, in one object.

Why this module exists
----------------------
The project this package was extracted from published numbers that moved when a
constant nobody had written down changed: a repeat count, an operator list, a
tolerance, a default reduction. Each of those constants lived at its own call
site, so "what did we run?" could only be answered by reading every harness.

The rule here is that a **tuning decision is configuration, not a fork**. If a
number could reasonably differ between what an open package ships and what an
organisation runs internally, it is a field on :class:`Profile` and it is read
from :func:`active` at use time. There is exactly one public profile,
:data:`PUBLIC`, and a documented hook for an overlay that lives outside this
repository.

An overlay is not a patch of this file. It is a separate module that builds its
own :class:`Profile` -- usually with :func:`derive` -- and is selected by the
``SPDELTA_PROFILE`` environment variable::

    SPDELTA_PROFILE=mycorp.bench_profile:INTERNAL python -m spdelta.example

That indirection is deliberate. A fork drifts silently; an env var that names a
module is visible in the process listing, reproducible from a shell history, and
recorded on every result row this package emits (see ``profile`` in
:func:`spdelta.harness.sweep`'s output).

Which knobs are expected to differ, and why
-------------------------------------------
=========================  ==================================================
Knob                       Why an internal overlay would change it
=========================  ==================================================
``steps``, ``repeats``     A dedicated, thermally pinned bench box can afford
                           20,000 steps and a full Latin square over arms. A
                           laptop running a doctest cannot. The public values
                           are chosen to finish in seconds, which makes them
                           the wrong values for a quotable number.
``operators``              The public list is *toy* operators generated by
                           this package. An internal overlay points at a real
                           corpus. This is the field most likely to differ and
                           the one most likely to be quoted past its warrant:
                           a ratio over three synthetic operators is not a
                           ratio over a corpus, and the operator list is what
                           decides which of those two you have.
``rho_grid``               The measured churn ceiling is a property of what
                           was actually run. Publishing a grid that stops at
                           0.25 and then quoting behaviour at 0.5 is the exact
                           error the ``rho_ceiling`` field on
                           :class:`spdelta.claim.Claim` exists to prevent.
``n_dirty``, ``batch``     Workload shape. Both change which arm wins, so both
                           belong to the caller's regime, not to a default.
``tolerance``              The public value is a strict correctness tolerance
                           for exact arithmetic. A harness whose fast arm is a
                           deliberately budgeted approximation needs a looser
                           one -- and needs to say so on the row, which is why
                           the tolerance is emitted rather than assumed.
``stat``                   Median by default: a page fault inside a
                           microsecond-scale kernel moves a mean by tens of
                           percent. An overlay measuring throughput rather
                           than latency may legitimately want a mean.
``rotate``                 Arm-order rotation defaults on. ``False`` exists so
                           the bias can be *measured*, and an overlay that
                           runs the paired rotated/fixed contrast will flip it
                           deliberately.
``reduction``              ``None`` in public, and that is the point: two
                           defensible reduction shapes exist, choosing between
                           them moves published numbers, and this package
                           refuses to choose on the caller's behalf. An
                           internal overlay is allowed to pin one, because an
                           organisation *can* make that decision once. See
                           :mod:`spdelta.harness`.
``bootstrap_reps``,        Cost/precision trade. Public is small enough to run
``bootstrap_alpha``        in a test suite.
``nnz_bands``              Resolution of the nnz-matched jump control. Too few
                           bands and the control stops controlling; too many
                           and bands run out of members to draw from.
``drift_radius``           How local "local" is. This is a workload property
                           and there is no universally right value.
=========================  ==================================================

No value in :data:`PUBLIC` came from an internal measurement. The toy operators
are generated here, from seeds written here, and are small on purpose.
"""

from __future__ import annotations

import importlib
import os
from dataclasses import dataclass, replace
from typing import Final

__all__ = [
    "ToySpec",
    "Profile",
    "PUBLIC",
    "PROFILE_ENV_VAR",
    "active",
    "derive",
    "load",
    "use",
]

#: The environment variable naming an overlay profile, as ``module:ATTRIBUTE``.
PROFILE_ENV_VAR: Final = "SPDELTA_PROFILE"


@dataclass(frozen=True, slots=True)
class ToySpec:
    """A generated operator, described rather than shipped.

    Descriptions rather than data files, so the public profile carries no
    measured artefact of any kind and a reader can regenerate every operator
    from what is printed on a result row.

    Attributes
    ----------
    name:
        Appears verbatim in result rows and in the reduction that groups by
        operator, so it must be stable across runs.
    kind:
        One of the generators in :mod:`spdelta.operators`.
    n_cols:
        Column count. Rows are decided by the generator.
    param:
        Generator-specific shape parameter -- bandwidth, grid side, or fanout.
    seed:
        Fixes the values, and for ``fanout`` the pattern too.
    """

    name: str
    kind: str
    n_cols: int
    param: int
    seed: int


@dataclass(frozen=True, slots=True)
class Profile:
    """A complete set of tuning decisions.

    Frozen because a profile that can be edited after a sweep starts is a
    profile that cannot be reported. Use :func:`derive` to make a variant.
    """

    name: str
    #: Timed steps per repeat.
    steps: int
    #: Repeats per (cell, arm). Each repeat re-prepares the arm and is asserted
    #: against the reference independently.
    repeats: int
    #: Right-hand-side width.
    batch: int
    #: Which statistic reduces per-step timings to the cell's number.
    stat: str
    #: Rotate arm order per cell.
    rotate: bool
    #: Relative L2 tolerance for the reference assertion.
    tolerance: float
    #: Churn rates to sweep. The largest is what a claim may state as its
    #: measured ceiling; above it, the honest word is "unmeasured".
    rho_grid: tuple[float, ...]
    #: Size of the dirty column set.
    n_dirty: int
    #: Bootstrap resamples over operators.
    bootstrap_reps: int
    #: Two-sided alpha for the bootstrap interval.
    bootstrap_alpha: float
    #: Geometric bands for the nnz-matched jump control.
    nnz_bands: int
    #: Neighbour radius for local drift.
    drift_radius: int
    #: Reduction name, or ``None`` to force the caller to choose.
    reduction: str | None
    #: Operators to sweep.
    operators: tuple[ToySpec, ...]

    def describe(self) -> str:
        """One line per knob, for pasting next to a number."""
        fields = [
            ("name", self.name),
            ("steps", self.steps),
            ("repeats", self.repeats),
            ("batch", self.batch),
            ("stat", self.stat),
            ("rotate", self.rotate),
            ("tolerance", self.tolerance),
            ("rho_grid", self.rho_grid),
            ("n_dirty", self.n_dirty),
            ("bootstrap_reps", self.bootstrap_reps),
            ("bootstrap_alpha", self.bootstrap_alpha),
            ("nnz_bands", self.nnz_bands),
            ("drift_radius", self.drift_radius),
            ("reduction", self.reduction),
            ("operators", tuple(spec.name for spec in self.operators)),
        ]
        return "\n".join(f"{key:<16} {value}" for key, value in fields)


#: The only profile this package ships. Small, fast, and synthetic.
#:
#: Nothing here is a measurement. The step and repeat counts are sized so the
#: worked example and the test suite finish in seconds on a laptop, which makes
#: them explicitly unsuitable for a quotable number -- and a number produced
#: under this profile carries ``profile='public'`` on every row saying so.
PUBLIC: Final = Profile(
    name="public",
    steps=64,
    repeats=3,
    batch=4,
    stat="median",
    rotate=True,
    tolerance=1e-9,
    rho_grid=(0.01, 0.05, 0.25),
    n_dirty=96,
    bootstrap_reps=400,
    bootstrap_alpha=0.05,
    nnz_bands=16,
    drift_radius=3,
    reduction=None,
    operators=(
        ToySpec(name="band_4k_w9", kind="banded", n_cols=4000, param=9, seed=11),
        ToySpec(name="grid_64", kind="grid2d", n_cols=64 * 64, param=64, seed=12),
        ToySpec(name="fanout_4k_8", kind="fanout", n_cols=4000, param=8, seed=13),
    ),
)

_ACTIVE: Profile | None = None


def derive(base: Profile, **changes: object) -> Profile:
    """A variant of ``base``, with ``name`` required to change too.

    Renaming is enforced because a result row records only the profile's name.
    Two different profiles sharing a name make the row a lie, and this package's
    whole position is that a number is worthless without its conditions.
    """
    if "name" not in changes:
        raise ValueError(
            "derive() requires a new 'name': result rows record the profile "
            "name and nothing else about it, so two profiles sharing a name "
            "are indistinguishable after the fact"
        )
    if changes["name"] == base.name:
        raise ValueError(f"derived profile must not reuse the name {base.name!r}")

    # rho_grid is validated HERE rather than three layers down where a motion
    # is finally constructed. Passing 0.0 used to be accepted silently at
    # config time and raise at run time, after the sweep had started -- and
    # the README's own private-overlay example did exactly that, so the
    # package's documented customisation path crashed on the package's own
    # proudest guard. PUBLIC.rho_grid correctly omits 0.0; the example did not.
    #
    # A configuration error should fail where the configuration is written.
    grid = changes.get("rho_grid")
    if grid is not None:
        bad = [r for r in grid if not (0 < float(r) <= 1)]
        if bad:
            raise ValueError(
                f"rho_grid contains values outside (0, 1]: {bad}. rho=0 in "
                f"particular is not a churn rate, it is the frozen control -- "
                f"the sweep adds it via spdelta.motion.frozen(), and listing "
                f"it here means a motion is built at rho=0, which is refused. "
                f"Drop it from the grid."
            )
    return replace(base, **changes)  # type: ignore[arg-type]


def load(spec: str) -> Profile:
    """Import a profile from a ``"module:ATTRIBUTE"`` string.

    The overlay hook. The imported attribute must be a :class:`Profile`; a
    duck-typed near-miss is rejected loudly rather than half-working, because a
    missing field would otherwise surface as an unrelated ``AttributeError``
    somewhere inside a sweep that has already burned an hour.
    """
    if ":" not in spec:
        raise ValueError(
            f"profile spec {spec!r} must be 'module:ATTRIBUTE', "
            "e.g. 'mycorp.bench_profile:INTERNAL'"
        )
    module_name, _, attr = spec.partition(":")
    module = importlib.import_module(module_name)
    try:
        candidate = getattr(module, attr)
    except AttributeError as exc:
        raise ValueError(f"{module_name!r} has no attribute {attr!r}") from exc
    if not isinstance(candidate, Profile):
        raise TypeError(
            f"{spec!r} is {type(candidate).__name__}, not a spdelta Profile"
        )
    return candidate


def active() -> Profile:
    """The profile in force.

    Resolution order: an explicit :func:`use`, then ``SPDELTA_PROFILE``, then
    :data:`PUBLIC`. The environment is consulted on every call rather than
    cached at import, so a test can set it and a caller can see it.
    """
    if _ACTIVE is not None:
        return _ACTIVE
    spec = os.environ.get(PROFILE_ENV_VAR)
    if spec:
        return load(spec)
    return PUBLIC


def use(profile: Profile | None) -> None:
    """Pin the active profile in-process; ``None`` restores env/default resolution."""
    global _ACTIVE
    if profile is not None and not isinstance(profile, Profile):
        raise TypeError(f"expected a Profile, got {type(profile).__name__}")
    _ACTIVE = profile
