"""Read tracking: proof that a derivation actually touched its data.

This is the structural check, and it exists because a value check cannot
replace it.

The instance it generalizes from: a chart script whose surrounding prose said
the curve was "re-derived directly from the CSVs". It was not. The script's
only file operation was `open("chart.svg", "w")`; the CSV paths appeared in a
comment; the curve itself was a list of hand-transcribed literals. The literals
were **numerically correct**, so every value-equality check over that script
passed. What made the claim false was not the numbers -- it was that no read
ever happened. Only a structural check can see that.

The same shape recurs whenever prose describes a *provenance* rather than a
value: "computed from", "read directly from", "regenerated by". Those are
claims about behaviour, and behaviour is what you have to observe.

## What this can and cannot see

Patched: `builtins.open` and `io.open` -- which together cover `open()`,
`pathlib.Path.open`, `csv`, `json.load` on a handle, and anything layered on
them.

⚠️ **`pathlib` reads are invisible on Python 3.10 specifically.** Measured
2026-08-05 across 3.9 / 3.10 / 3.11:

    (3, 9)   Path.read_text  observed=['results.csv']
    (3, 10)  Path.read_text  observed=[]          <-- sees nothing
    (3, 11)  Path.read_text  observed=['results.csv']

3.10's `pathlib._NormalAccessor` binds `io.open` at import time, before this
patch is applied; 3.9 and 3.11+ resolve it at call time. So the sentence above
is true on every version this package supports (`requires-python = ">=3.11"`)
and false on the one immediately below it. It is written down rather than
quietly relied on, because the failure direction is the bad one: a derivation
that reads its data through `pathlib` would report reading NOTHING, and
`assert_reads` would fail an honest derivation while a bare `open()` in the
same file passed. The floor declared in pyproject.toml is what makes this a
footnote rather than a defect.

Not patched: readers that open files in C without going through Python's
`open` -- `numpy.load`, `pandas.read_csv` on some engines, `sqlite3.connect`,
`h5py`, extension modules generally. For those, pass `extra_patches` naming
the symbol to wrap, or track a lower-level call yourself. `assert_reads` will
tell you when it saw nothing at all rather than quietly asserting an empty set,
because "no reads observed" is exactly as suspicious as "the wrong reads".
"""

from __future__ import annotations

import builtins
import contextlib
import io
import os
import runpy
import shutil
import tempfile
from dataclasses import dataclass, field
from typing import Any, Callable, Iterable, Iterator, Sequence

__all__ = ["ReadLog", "track_reads", "record_reads", "assert_reads", "reads_of_script"]


def _is_read(mode: str) -> bool:
    """A mode that can read. 'r', 'rb', 'r+', 'w+' and 'a+' all can."""
    return "r" in mode or "+" in mode


@dataclass
class ReadLog:
    """Every path opened for reading, in the order it was opened."""

    paths: list[str] = field(default_factory=list)

    @property
    def names(self) -> list[str]:
        return [os.path.basename(p) for p in self.paths]

    def saw(self, needle: str) -> bool:
        """True if any recorded path ends with `needle` (basename or suffix)."""
        target = os.path.normpath(needle)
        for path in self.paths:
            normal = os.path.normpath(path)
            if normal == target or os.path.basename(normal) == target or normal.endswith(os.sep + target):
                return True
        return False

    def __len__(self) -> int:
        return len(self.paths)

    def __repr__(self) -> str:  # pragma: no cover - convenience
        return f"ReadLog({self.names!r})"


@contextlib.contextmanager
def record_reads(extra_patches: Sequence[tuple[Any, str]] = ()) -> Iterator[ReadLog]:
    """Context manager recording every path opened for reading inside it.

    `extra_patches` is a sequence of (module_or_object, attribute_name) pairs
    naming further open-like callables to wrap; the first positional argument
    of each is recorded as a path.
    """
    log = ReadLog()
    originals: list[tuple[Any, str, Any]] = []

    def wrap(original: Callable[..., Any], always_read: bool = False) -> Callable[..., Any]:
        def wrapper(file: Any, mode: str = "r", *args: Any, **kwargs: Any) -> Any:
            effective = kwargs.get("mode", mode)
            if always_read or _is_read(str(effective)):
                try:
                    log.paths.append(os.fspath(file))
                except TypeError:
                    log.paths.append(str(file))  # file descriptors, streams
            return original(file, mode, *args, **kwargs)

        return wrapper

    targets: list[tuple[Any, str, bool]] = [
        (builtins, "open", False),
        (io, "open", False),
    ]
    targets += [(obj, attr, True) for obj, attr in extra_patches]

    for obj, attr, always in targets:
        original = getattr(obj, attr)
        originals.append((obj, attr, original))
        setattr(obj, attr, wrap(original, always))
    try:
        yield log
    finally:
        for obj, attr, original in reversed(originals):
            setattr(obj, attr, original)


def track_reads(
    fn: Callable[..., Any],
    *args: Any,
    extra_patches: Sequence[tuple[Any, str]] = (),
    **kwargs: Any,
) -> tuple[Any, ReadLog]:
    """Run `fn(*args, **kwargs)` and return (its result, the read log)."""
    with record_reads(extra_patches) as log:
        result = fn(*args, **kwargs)
    return result, log


def assert_reads(
    fn: Callable[..., Any],
    expected_paths: Iterable[str],
    *,
    forbid: Iterable[str] = (),
    args: Sequence[Any] = (),
    kwargs: dict | None = None,
    extra_patches: Sequence[tuple[Any, str]] = (),
    why: str = "",
) -> Any:
    """Assert that running `fn` opens each of `expected_paths` for reading.

    Matching is by basename or path suffix, so a test does not have to know the
    absolute location of the data.

        assert_reads(build_chart, ["results.csv"],
                     why="RESULTS.md says the curve is read from results.csv")

    Returns whatever `fn` returned, so it composes with a value check -- and
    you want both. The structural check proves the read happened; the value
    check proves what was read is what was used. Neither implies the other.
    """
    expected = list(expected_paths)
    if not expected:
        raise AssertionError(
            "assert_reads called with no expected paths -- that assertion cannot fail, "
            "which makes it worse than absent (VACUOUS_TESTS.md #7)."
        )
    result, log = track_reads(fn, *args, extra_patches=extra_patches, **(kwargs or {}))

    missing = [p for p in expected if not log.saw(p)]
    if missing:
        seen = ", ".join(log.names) if log.paths else "NOTHING was opened for reading"
        reason = why or (
            "A provenance claim in prose is a claim about behaviour. Correct-looking "
            "literals pass a value check and leave the claim false."
        )
        raise AssertionError(
            f"{getattr(fn, '__name__', fn)} never opened {missing} for reading.\n"
            f"  opened: {seen}\n"
            f"  {reason}\n"
            f"  (If the reader is a C extension, see reads.py's docstring on extra_patches.)"
        )
    banned = [p for p in forbid if log.saw(p)]
    if banned:
        raise AssertionError(
            f"{getattr(fn, '__name__', fn)} opened {banned} for reading, which this "
            f"binding forbids. opened: {log.names}"
        )
    return result


def reads_of_script(
    path: str | os.PathLike[str],
    *,
    in_scratch_dir: bool = True,
    run_name: str = "__bindnum_read_probe__",
) -> tuple[dict, ReadLog]:
    """Execute a script and return (its module namespace, the read log).

    `in_scratch_dir` runs it from a temporary working directory so any files it
    writes land there and not in the repository. The returned namespace is what
    lets the *second* check happen: that the values the script plotted are the
    values its derivation produces.
    """
    script = os.fspath(path)

    def run() -> dict:
        return runpy.run_path(script, run_name=run_name)

    if not in_scratch_dir:
        return track_reads(run)

    scratch = tempfile.mkdtemp(prefix="bindnum_reads_")
    cwd = os.getcwd()
    try:
        os.chdir(scratch)
        return track_reads(run)
    finally:
        os.chdir(cwd)
        shutil.rmtree(scratch, ignore_errors=True)
